org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=de.jo_field
archives_base_name=BossbarHider

# Dependencies
fabric_api_version=0.153.0+26.2
fabric_kotlin_version=1.13.12+kotlin.2.4.0

# ModMenu https://modrinth.com/mod/modmenu/versions
modmenu_version=20.0.1
placeholder_api_version=3.1.0-beta.1+26.2

# Cloth Config
cloth_config_version=26.2.155