org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=1.0.1
maven_group=de.jo_field
archives_base_name=BossbarHider

# Dependencies
fabric_api_version=0.162.0+26.3
fabric_kotlin_version=1.14.1+kotlin.2.4.20

# ModMenu https://modrinth.com/mod/modmenu/versions
modmenu_version=21.0.0
